name: Playwright Automation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            pw-browsers-${{ runner.os }}-

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps chromium firefox webkit

      - name: Create .env from secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
          

      - name: Run smoke tests
        env:
          CI: true
        run: npx playwright test tests/smoke

      - name: Upload HTML report (smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-smoke
          path: playwright-report
          if-no-files-found: ignore

  performance:
    needs: smoke
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            pw-browsers-${{ runner.os }}-

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps chromium firefox webkit

      - name: Create .env from secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env

      - name: Run performance tests
        env:
          CI: true
        run: npx playwright test tests/performance

      - name: Upload HTML report (performance)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-performance
          path: playwright-report
          if-no-files-found: ignore

  regression:
    needs: smoke
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            pw-browsers-${{ runner.os }}-

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps chromium firefox webkit

      - name: Create .env from secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env

      - name: Run regression tests
        env:
          CI: true
        run: npx playwright test tests/regression

      - name: Upload HTML report (regression)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-regression
          path: playwright-report
          if-no-files-found: ignore

  e2e:
    needs: regression
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-browsers-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            pw-browsers-${{ runner.os }}-

      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps chromium firefox webkit

      - name: Create .env from secrets
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env

      - name: Run e2e tests
        env:
          CI: true
        run: npx playwright test tests/e2e

      - name: Upload HTML report (e2e)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-e2e
          path: playwright-report
          if-no-files-found: ignore
